[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Devin AI <158243242+devin-ai-integration[bot]@users.noreply.github.com>"]
package-mode = true

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.115.7"}
psycopg = {extras = ["binary"], version = "^3.2.4"}
pandas = "^2.1.4"
numpy = "^1.26.3"
scikit-learn = "^1.3.2"
yfinance = "^0.2.35"
transformers = "^4.36.2"
torch = "^2.1.2"
python-dotenv = "^1.0.0"
nltk = "^3.8.1"
httpx = "^0.26.0"
uvicorn = "^0.27.0"
aiohttp = "^3.11.11"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
